#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.ipsl.upmc.fr - 2025/06/23 12:35:50
# Search URL: https://esgf-node.ipsl.upmc.fr/esg-search/wget?distrib=true&latest=true&replica=true&realm=atmos&project=CMIP6&experiment_id=historical&frequency=mon&table_id=Amon&member_id=r1i1p1f1&variable=tas&source_id=EC-Earth3-Veg-LR&limit=10000
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.ipsl.upmc.fr/esg-search/wget?distrib=true&latest=true&replica=true&realm=atmos&project=CMIP6&experiment_id=historical&frequency=mon&table_id=Amon&member_id=r1i1p1f1&variable=tas&source_id=EC-Earth3-Veg-LR&limit=10000'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185001-185012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185001-185012.nc' 'SHA256' 'd9a840d8afd0c819bfcd0117ce2b365f1ba439d7c7e94eb3a65d96e6fe2d700b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185101-185112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185101-185112.nc' 'SHA256' '03bc9658d49394e2810bc2d2f22323e5e96b7a8a5671e62b6748841d6f615a02'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185201-185212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185201-185212.nc' 'SHA256' '098868a29dc464951445a99ed0f03c5967118aa2b56af496d92eeefb67466bee'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185301-185312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185301-185312.nc' 'SHA256' '1666062119134f8e0a5f5bd25607ca505a5479b40e071b7f0ec9b046c3d67dcc'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185401-185412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185401-185412.nc' 'SHA256' 'e9582fa907f8b5e04baeafffcc2959dc526b7980922024de34858cc339adce06'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185501-185512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185501-185512.nc' 'SHA256' '86c96490cdb07636722ff1f94a69a5b2dbabccf4b1939856ec22851c066b5026'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185601-185612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185601-185612.nc' 'SHA256' 'e6db392cd3cfbb4dc2433d54de1bbcff63f0f2962cceac72b6193eba26559a97'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185701-185712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185701-185712.nc' 'SHA256' '6a9d913dbc7d72dd763d9563f9886e86e513cdc7388f3d84fe5ec8df00b8e66b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185801-185812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185801-185812.nc' 'SHA256' '8428b4671140d36239bf51f7c07fa83c5fcd48e9fe0b14d8aa1cc327ee26f215'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185901-185912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_185901-185912.nc' 'SHA256' 'f6711ffe932c4e00ce838243d953d705d4718ead429d487d1c745659068e3417'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186001-186012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186001-186012.nc' 'SHA256' '911299f6c4d7306aa737673bb6b39884aebc2163d447e0c211afcaba41d1dc8a'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186101-186112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186101-186112.nc' 'SHA256' '329a37bfecf4434edb41465ef2c69dc662115b053019264b574fec4d03463288'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186201-186212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186201-186212.nc' 'SHA256' '8d2898e859be0ffdf8f64a494c430f4787b0c54de3c015193ebfef485e8a6a69'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186301-186312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186301-186312.nc' 'SHA256' '77395c74a45fcb8761a75f68eac381128ea80ea23776fed5fde96f5a26d0c5bf'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186401-186412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186401-186412.nc' 'SHA256' '4c86151b02dc9d5ab59cb7a6509d06e79554043dd3ae2dfbb5677366802112a3'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186501-186512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186501-186512.nc' 'SHA256' '3a6a8a5ae277f05a6544f5c2761d17efd1815a92070b0fb7cceb2f5be80b0de9'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186601-186612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186601-186612.nc' 'SHA256' 'd1652ccbd4fb543dd1b0426181397f59c912a3889fe9b732f4892cac1b6d8f40'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186701-186712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186701-186712.nc' 'SHA256' '7edc4121baa9f7876b205fd7823b29b7e1e476397866a4de35a7a1b1fdc4413d'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186801-186812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186801-186812.nc' 'SHA256' '75adcdcd9a72723fc9f38e23ff98c4a6dc10414cf0612964c081ba2f67abd39a'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186901-186912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_186901-186912.nc' 'SHA256' '89968b37d0c4d0d2be806d4d9d704dd47d434f8755678e6d823cc38dd5fc70e7'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187001-187012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187001-187012.nc' 'SHA256' 'c331e32a3f1a774eec67f28d58925f06ff1b3fa8c6c2879c82dc3f304f95dcd6'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187101-187112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187101-187112.nc' 'SHA256' '15f1bde637d749e714ba41e86074bd6d3b622a47b38785c7e547c757257f3800'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187201-187212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187201-187212.nc' 'SHA256' 'bb26fb043ca1b21ae0e7834b2d89a3205051e6e9fac65c0a56b5ccf806cbe10f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187301-187312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187301-187312.nc' 'SHA256' 'a890b660edad0242b2644590ab240abd5a97f0e793809055f1dabf0e5ab2f9e6'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187401-187412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187401-187412.nc' 'SHA256' '10be856664c370c3aacd37f95f5d0ae00f5b917d05396bbaa8204bddaf16c456'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187501-187512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187501-187512.nc' 'SHA256' '3fe9f418a96ca86cf1646c3866af7e8743c4072eab451319f1fc2e707bf7ea8e'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187601-187612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187601-187612.nc' 'SHA256' 'e6c2519bffff99c536ae0461592d083bd96aff16a58ef2b97f472d6a1a512519'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187701-187712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187701-187712.nc' 'SHA256' 'd016c96d53702c6334a7fd318b65928cb7bae1eb15a8e15b29369e31eee44e79'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187801-187812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187801-187812.nc' 'SHA256' '22d4a5bca9ce8eeb72c791181c16963ab8a9e7efc15409e1f7e817f0e3f16ab3'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187901-187912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_187901-187912.nc' 'SHA256' '87d7d9c2983dcf697de0812b38a47baa2eaf415d5abf479c004c4c0259ebe684'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188001-188012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188001-188012.nc' 'SHA256' '5b6b8c87570098f6124a0033c9e5956416ba602d99dfed0fd33aed6c004691d2'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188101-188112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188101-188112.nc' 'SHA256' 'ff67fc9c585a9236278c2f88ae6cfaceeb8dd9a2a2a817ed30315664a1d8a902'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188201-188212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188201-188212.nc' 'SHA256' '90d8cf9d64469301996557e2005b77929f430a99fe36768fabcc662ea8740bae'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188301-188312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188301-188312.nc' 'SHA256' '1f4168a747c5fd6746b11a201d11e020dc403af49dfa59716884858d9de0a262'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188401-188412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188401-188412.nc' 'SHA256' '114ee69c9d7a4961c0c77c0e9a0a908dea87cc96ec0f2c57cbd836f3c46e5a99'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188501-188512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188501-188512.nc' 'SHA256' '65e0370bd0153c6b3b7eca16bccb6fb86a5e4b4f0a955f98ea732d94b5f0b707'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188601-188612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188601-188612.nc' 'SHA256' '48c502f962caf5024798806bcfcacde3b4a7e964dc404d82b7514528a18a89bd'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188701-188712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188701-188712.nc' 'SHA256' 'b842a9272527d3076641177866a577a20588e9cdf942aa2c25ee8c4f734bac32'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188801-188812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188801-188812.nc' 'SHA256' '877e912b024e094400b8c723917054a88bc91c02de3c864b4725877a84b7cdc5'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188901-188912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_188901-188912.nc' 'SHA256' '2449412d4173fa7a192b9624957f6663990e0a6a6d607d5107531768a5db2b92'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189001-189012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189001-189012.nc' 'SHA256' '163100d7081a47e7be9fb2693f8a2225c5711e223b0c42497f7db7f27d113781'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189101-189112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189101-189112.nc' 'SHA256' 'a85a4529a8c0009ea2264dc0d4800fa7abc2c3fffb547b5fefcd9a57a37aacc5'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189201-189212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189201-189212.nc' 'SHA256' 'e9f3838c89eec7951b20572834f86544a99c5f465315e12f6b0cd54c2d4a2fe8'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189301-189312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189301-189312.nc' 'SHA256' 'a2bc71d8e21fabf739151501ff75f158f929a0b2fda06d2b167afa97da3a48db'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189401-189412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189401-189412.nc' 'SHA256' '52fbf9bc894628ce89d547e196ee85dc4d3d50be2b13ca6123d6a9cb37fd9447'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189501-189512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189501-189512.nc' 'SHA256' '0339e6aad913e369d09c431ed6699dc7b0b317c2fa9d0d5b81d9604973a40c0b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189601-189612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189601-189612.nc' 'SHA256' 'b8222d35b8f051ec5accb7647dd477c882b1a066e8a3ecbc94bad20044306615'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189701-189712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189701-189712.nc' 'SHA256' '65b49b512cd2cd8107c30b47f31c23cd122599bab551ba7036494fedccd45124'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189801-189812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189801-189812.nc' 'SHA256' '6eb372509037e93b1825465aa485c7764d099ecc1e5e6f9701f8c332f13acb23'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189901-189912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_189901-189912.nc' 'SHA256' '065f7beb07fa87e0bf0b6b42dc27f11bd90336239191fc0fdfcea318100bfed4'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190001-190012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190001-190012.nc' 'SHA256' '6df456a69b54a767e6498164f7ef3aef055bedee5e951e46d3efea9c310c2a4e'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190101-190112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190101-190112.nc' 'SHA256' 'efdf462a91b104dcf6794ebadcb7b9e6872f637bd386d97243b189af47fa9209'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190201-190212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190201-190212.nc' 'SHA256' 'c39932a535d68a8051a687d822e114ca1a838abe3c34871ed89006773c092d88'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190301-190312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190301-190312.nc' 'SHA256' 'fd0365521f7b864bf8b8a9358202333a98e04b41c6c749d0c9bab58be777beef'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190401-190412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190401-190412.nc' 'SHA256' '47b4ab4657108ec69e9e38d08d471591c74ec6e01dc151dd7e3cc99f76337807'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190501-190512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190501-190512.nc' 'SHA256' '92c66c4c3ae0651164c63b1aa4cc20b753b206aa653cd9612acbd6de0f48911f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190601-190612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190601-190612.nc' 'SHA256' 'faa1294a3684d91a4764ca1ee007735a91eb4c2b2c98909ce64190b2e162b1ec'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190701-190712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190701-190712.nc' 'SHA256' 'fe1f950ca33e014283a7a80168134f4a26cafbb6b46583bdc0614984016a14d5'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190801-190812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190801-190812.nc' 'SHA256' 'f60dff452f0553b555cec2f0dd0b3da529032a240869aa9918dd30307dfb22a6'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190901-190912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_190901-190912.nc' 'SHA256' '195b841d4d63b6ad22d5952a16319633fcea393fa723c6846900a82604d6f673'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191001-191012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191001-191012.nc' 'SHA256' '1a61655c3dff221196f2f09955c405fbab26de46c19a3b1697ae120f55f3ee3b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191101-191112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191101-191112.nc' 'SHA256' '7f3d5c53333d85606b100cecfcc62ddf8dc2c227d11b2049e1a180e84fd621e1'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191201-191212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191201-191212.nc' 'SHA256' 'c36161380c06cb9646cd5b6419240c83d7ede479166110e16b64199c115f272b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191301-191312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191301-191312.nc' 'SHA256' '69395fb5c6cba20a76ec56ee25ba420c4a37954156ec84815900240ec0b5cab9'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191401-191412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191401-191412.nc' 'SHA256' '98b680cec618ee2fce3bf6015d9f396e021435274762402d73e0c54f9b4de7be'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191501-191512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191501-191512.nc' 'SHA256' '8f09277deb92271ad43a0142983268ff1ea0b61e03f671fcefa2aefaaa968822'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191601-191612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191601-191612.nc' 'SHA256' '30d8e009ef391fce0fe5eb1d02e9deae1273ba1711d9159ff73a1750907d8091'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191701-191712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191701-191712.nc' 'SHA256' '53119a6bbe7304119a366bd6e1f1605737add9691102d897e6149ab294550557'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191801-191812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191801-191812.nc' 'SHA256' '1c2d24ba821331f06b3df51031035cb7e4295503afe83c9063d2e4d8e0499f98'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191901-191912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_191901-191912.nc' 'SHA256' '3c070a4f45b4570d52a966b972a83b8c238fdc59695037dbf6f0b48a088904e0'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192001-192012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192001-192012.nc' 'SHA256' 'a8a523dd525e2d0074fb361ee61a441e77249264fee0f7240a55dc9924d1c8c9'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192101-192112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192101-192112.nc' 'SHA256' '7fc070cbbb67eaaabc7849f27e65e4e2e610814707076d1015ed6a1a013fe36d'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192201-192212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192201-192212.nc' 'SHA256' '0d4fc2f3354f3fb2e8a3949b19aec6c31db492d24ce276b7c32526ea8f9c41a7'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192301-192312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192301-192312.nc' 'SHA256' '160f23f50b7fba9ddd0275f2bb3761eaf0bcbd31c8ebc1779c30014dcccefefe'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192401-192412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192401-192412.nc' 'SHA256' 'c58fa3a70deb038454e64287a158baa192e1b213f5147d0a0d04304e9bfc3897'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192501-192512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192501-192512.nc' 'SHA256' 'a0535ea122a98d6d9a03640bbf5ed464d66cdb75d359aad6aa4d9c2f36823bcb'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192601-192612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192601-192612.nc' 'SHA256' '9224c6c10404dd56bb785fccfcdb28735f198590bdc4035a4e97ebd79118db3d'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192701-192712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192701-192712.nc' 'SHA256' '57ed7e31effad3fe5fa09cddb0dff0f80a71b8276ab8388b10d210f6ccd44f41'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192801-192812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192801-192812.nc' 'SHA256' '431324b459c4f7271fc4492eaa7a737a41796546b9a0c4ec32b735c850eda476'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192901-192912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_192901-192912.nc' 'SHA256' '47ae614f8c773796c4e1b24947e78401c10d97e93f1312dc2a597cfea8aaa7d3'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193001-193012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193001-193012.nc' 'SHA256' '1e16a32149d3524355c2a9d583bbdcd0166a2a90404d8537f07aebe8a6458332'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193101-193112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193101-193112.nc' 'SHA256' 'd8b0865d90b871d8ca565d7306ff0f18239618700beade72ba64bae39f790569'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193201-193212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193201-193212.nc' 'SHA256' '834b122071a6cd0150614665f6c449b381ec110ddec7f8116c7cd3b670d5bce6'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193301-193312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193301-193312.nc' 'SHA256' '16a9409d192e44e9320b70523965df9ded0bafb7513bbe38d255824f113ec168'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193401-193412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193401-193412.nc' 'SHA256' 'a11cc78fa99bc5624c2300835f9b18254c0e570c29e25f33ea995740ae48ba86'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193501-193512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193501-193512.nc' 'SHA256' 'a11a901afc06658b1107160edeb336bf3461ae962fae0b988db2b745bf4fe13f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193601-193612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193601-193612.nc' 'SHA256' '67d5a0b5a1a6257fb9e7c41e7b4e79a8ca4690c930dc6ce912e6ad5004875730'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193701-193712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193701-193712.nc' 'SHA256' '17ccd70c3a78669792554e555a4f7817fe19877b7714787f65bf69dd6d90da65'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193801-193812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193801-193812.nc' 'SHA256' '9c16234015616464218a365d93ac66154ebf38f1c97070b970add715d9afda1f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193901-193912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_193901-193912.nc' 'SHA256' '1b61e2d77e8efdeee3e4050b857e7eab5f455a7766fff4092606468e9642d507'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194001-194012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194001-194012.nc' 'SHA256' 'd645c6041a802286d96f2475c4bfddda2fec3f94a26b14b271df8a82f71299bd'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194101-194112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194101-194112.nc' 'SHA256' '88b60b7ff93f27a7118ced635673862c2a768712f3421bdf4aacb4e45d297618'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194201-194212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194201-194212.nc' 'SHA256' 'fcb6cc04464e3a826274697c12047a13c97e7567ccf3bc3e20e126c74e67544b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194301-194312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194301-194312.nc' 'SHA256' 'a3060fa563ee4d9b7061b630d7b6c9fdb2b0a87d0956aa9deb5236f8a56bb07b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194401-194412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194401-194412.nc' 'SHA256' 'dbfd64e75820b78bbad5aad7f064e784bb1b5bff3a06343ad6d4cfa4d4876653'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194501-194512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194501-194512.nc' 'SHA256' '93bd1df989433b4449926c831f76533adc8ca7e3289e02980c7e8c3423f7b5c4'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194601-194612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194601-194612.nc' 'SHA256' '2e3adc00e8f29ad6223875aae661a91969a7c2bb936ea7982889adf9edcf0c54'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194701-194712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194701-194712.nc' 'SHA256' 'c4f60f682554524bae8ee14559537dd3852e73d68c196c9380e8e582826e8733'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194801-194812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194801-194812.nc' 'SHA256' 'f90810253c158939f27fe90420fceddac7ceece89106d579d76d2b35d4d045fa'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194901-194912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_194901-194912.nc' 'SHA256' '81f96edaaff082416acdbc23e4b6c283dc3c25e20d6c69e76cf36617f80fc7d8'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195001-195012.nc' 'SHA256' 'df2432207b7c86ae6b94d0c743e9a53c5cb06c2f90c75a141f71989842797b4b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195101-195112.nc' 'SHA256' 'a8f333806ee1e28cfca70855b740580e17fe1ca205c1ae9e8c36c918bf655b30'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195201-195212.nc' 'SHA256' '062923bb92653253096971f13d73ecc7c1b965b621030607d15ce8130a10d416'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195301-195312.nc' 'SHA256' '36346ffec6d10e73ef18137678fbadadeb0abc8c872d94500c9b75850b82cc16'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195401-195412.nc' 'SHA256' '6ec0e878e5826cfe00ce90a4ea5e47410db3b2bec7fa96616b112ec1e874b21d'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195501-195512.nc' 'SHA256' '27952bf2b0358df684968ab0a6346e579f6ac7a1b72a126c7865b9b24e688b83'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195601-195612.nc' 'SHA256' 'b644fabe892b382fa8fd4d46af917704a27cdf1291e2d64ba3376c068f15a1ef'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195701-195712.nc' 'SHA256' 'c25a49ecf850feccbf5e6248c3f34fc04fabc17ad7d2fc911251637116bcfa1b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195801-195812.nc' 'SHA256' 'db31df33bdb1f446c9fa911a7aff8b25ecd0407eb2140ffebd90f2f341ac35e3'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_195901-195912.nc' 'SHA256' '1961cbe1ffc7e5a8ee9bd3b3e3ba5e99c2389ad4e4de5d5059ac205ff17dc99a'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196001-196012.nc' 'SHA256' '781daea0ceebadc995adaea570eff0ccafd37c9cdcbdbeece22a8ca34c9cc09f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196101-196112.nc' 'SHA256' 'f92b51d7411fa8ead8f6ebaa4566717ca4b21f31ea570343cb4d0e98a0ddd9b2'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196201-196212.nc' 'SHA256' '4ccdc15f5bc103188fed5908022ed342ebc78217f5c0315e27f22db0f30e2aed'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196301-196312.nc' 'SHA256' '19b280a1f51246c0c7936a900a72d44709848ae4ec79c40a499f93e8d4c5a5dd'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196401-196412.nc' 'SHA256' '8c77a68824a4ef2b8b06dfb7549580876c955843ecd8c642f364b19f599c7e4b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196501-196512.nc' 'SHA256' '2c8d65448fad248bff9a4b54f1b12c0b24ea56db4af19285d8f2360c5a9bad18'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196601-196612.nc' 'SHA256' 'b9361be169b806a2926edb47d5f823cfa090a56be27618c25a652be068aea20d'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196701-196712.nc' 'SHA256' '37afc95d838f34fffc621fbe886349eba941ba63b0c3b0b2750133a043b3751f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196801-196812.nc' 'SHA256' '58cbf7458946496965cf4f822350186be889ae16b1c0cca15c4dfa4f18c91a81'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_196901-196912.nc' 'SHA256' '580e49f18aae7917d6860328bed21ed367a8a095d97d922ba8cddacbb36dd71f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_197001-197012.nc' 'SHA256' '3482e820b29081d4e09624be1523fa5991f6282717a4b5785ff7730fab42a1ef'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_197101-197112.nc' 'SHA256' '341e3fdaaf6d324cf976402b7dd638a6677bfbcdc99c0353de3a13e29eddf4b2'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_197201-197212.nc' 'SHA256' 'e9b9f7b8af01941add97ac6e6d24389bc253f354824627b30223fdca7f73f596'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_199601-199612.nc' 'SHA256' '999b3838f5487f843ed2610d03f70d6318fb29e3abdddb5197f050b6a6b2888e'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_200101-200112.nc' 'SHA256' '76a72cf6bdd2ba020822825c6be12727a46c4845dfee4aeb844ead60134e076f'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_201201-201212.nc' 'SHA256' '667dd26176a89c73374c48ac0f8cef0effb08ac7fe47461f2b4c04824569bd69'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_201301-201312.nc' 'SHA256' '5cc62750ba328d11adcb8f1123d0ea79642c13e7c379047a35ae348a98d7621b'
'tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3-Veg-LR/historical/r1i1p1f1/Amon/tas/gr/v20200217/tas_Amon_EC-Earth3-Veg-LR_historical_r1i1p1f1_gr_201401-201412.nc' 'SHA256' '3785dd82aaa1b084c5df4d581de07e0297b247ef0f73d3ecb8ede0f026f91359'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 128 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
