#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.ipsl.upmc.fr - 2025/06/23 12:35:47
# Search URL: https://esgf-node.ipsl.upmc.fr/esg-search/wget?distrib=true&latest=true&replica=true&realm=atmos&project=CMIP6&experiment_id=historical&frequency=mon&table_id=Amon&member_id=r1i1p1f1&variable=pr&source_id=EC-Earth3&limit=10000
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.ipsl.upmc.fr/esg-search/wget?distrib=true&latest=true&replica=true&realm=atmos&project=CMIP6&experiment_id=historical&frequency=mon&table_id=Amon&member_id=r1i1p1f1&variable=pr&source_id=EC-Earth3&limit=10000'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185001-185012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185001-185012.nc' 'SHA256' '1a5cdc098cabd6f3a500a557ba9a7a74a91fe20355afd2f2ec9891633fa32d1c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185101-185112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185101-185112.nc' 'SHA256' 'da7f12d8706a7e08292f3f640f86bfea5163b5cd21f4b8ca5d599910a0b4843b'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185201-185212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185201-185212.nc' 'SHA256' 'b3414babce938f7138f4eaa2df406090a9e050b74bea936a371190c39bb0a081'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185301-185312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185301-185312.nc' 'SHA256' '9553893c7beff6b84d3dcd59e12f2d82e9d4d5798328c9a990e37414e81d2a7f'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185401-185412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185401-185412.nc' 'SHA256' '70861299a10c5676a44c6f7606eb451318f1715e189985e9e0c7db4ca2ccc3ab'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185501-185512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185501-185512.nc' 'SHA256' '855f4fb33f7676026b6937fe5296fcd618e72c0568c2bb2844df585bd8ae580f'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185601-185612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185601-185612.nc' 'SHA256' '8c1cb7874b40484b7c7476a3075c53ee56ff577d1b44605a8f6ba864e7312bb4'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185701-185712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185701-185712.nc' 'SHA256' '37524d514038b1436847a90db94b680ffc31076b44f6d6ad15fb46d949d57d6d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185801-185812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185801-185812.nc' 'SHA256' 'e55e3a4d44ae70eaed5b22d840fc0ec035d3d3ec7d90a7c38dcf2485ffe5708f'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185901-185912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_185901-185912.nc' 'SHA256' '98ecaf0835d8ad5d221886232e17abd6f69bb1b512cc69de4f07787cf7185ce6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186001-186012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186001-186012.nc' 'SHA256' 'b4894722319bf5dec8b179781444e00fd5a6eb99d66a5c9d77f58b44605cea9d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186101-186112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186101-186112.nc' 'SHA256' '234d2d439341e5e15a54dcc467fecc529f1d4b91dc2179eef1ee4d342c92838e'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186201-186212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186201-186212.nc' 'SHA256' 'e1522c15140c759c1a3599c2b9fe05627d76edfa27f93325056d62e4f4be70c3'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186301-186312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186301-186312.nc' 'SHA256' 'a81e8be327d3fa454fa15bdac181a23b1426029a58c29f3c666aa0f2a9548b85'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186401-186412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186401-186412.nc' 'SHA256' '45a6770fee46a3aaa709ac52293620d8fefb53ab09ab61eb92b25ddc8b0df42a'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186501-186512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186501-186512.nc' 'SHA256' 'c8fd1c6e90b213452dbaa4b55adeb99394d63ab314666fbdb5e5ca866ed69072'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186601-186612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186601-186612.nc' 'SHA256' '4bb013f89c0169698d95530b24e471c439d74ca9ab373eb5cf8cee23027738eb'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186701-186712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186701-186712.nc' 'SHA256' '8565ac770b5fca142c58253b1eb75fad22f632a3d8468b62b9c63069d2fe33e6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186801-186812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186801-186812.nc' 'SHA256' 'f3538dfc17ebb359d1f59963c82ddc95c3e42ed46a4cf81ccc20d76dd9e4d795'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186901-186912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_186901-186912.nc' 'SHA256' '76c4f027bffcf3632c241669f6521d3bac83e43c04e263e11e08c53bbd443637'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187001-187012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187001-187012.nc' 'SHA256' 'd06c38b3230d21f44360e2fd54ddff6868c30b9c1b223399667655fb5ee3a800'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187101-187112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187101-187112.nc' 'SHA256' 'b20d97f964b9fa4d96f041384d7c9079ca4c1e9ed136910cc305bc47d87177de'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187201-187212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187201-187212.nc' 'SHA256' 'e541a649deda482d565699aa81c1f4ee4b8a50157abba7102f75ad2f0d761650'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187301-187312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187301-187312.nc' 'SHA256' '38284f14055446d9c76bfdba88d17a441a965aaad7cab9298e066b3d2a00b6bf'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187401-187412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187401-187412.nc' 'SHA256' '041734b8f0137fded8de7f9c10a4390b3af7e67509ade503212081b4979014c6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187501-187512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187501-187512.nc' 'SHA256' '134305c08efcc0245862b9b5f48ac15273c78b493b1230dbf1aac1182a09c65d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187601-187612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187601-187612.nc' 'SHA256' 'd5f21c55694832365bf63cff776eb1cf30abf61754d9a1a599465ccde2d1ed65'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187701-187712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187701-187712.nc' 'SHA256' '6ec1adfed41ae4e14f954224bd02451518cba9a0bcb67e07732e41f58d6636e5'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187801-187812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187801-187812.nc' 'SHA256' 'd17930eabafd62aebbbae0227cde54bb1bfd27cfce7be354485a63438300369c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187901-187912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_187901-187912.nc' 'SHA256' 'a4822cf18dce5c7e4ebc594886720e4b8258be979789828f4827bc997291fa20'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188001-188012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188001-188012.nc' 'SHA256' 'b5aec3529163ef39216f30fc01a376a7458928e505d8c2933d11451982bc58d3'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188101-188112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188101-188112.nc' 'SHA256' '033f6d56cdd02629832816ff2d6295aed85fdf77ccf593833cde39ed2ea60842'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188201-188212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188201-188212.nc' 'SHA256' 'da73613f4b1527c84549f04a918df61cec46e072ad97fa2844202621e6134ac8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188301-188312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188301-188312.nc' 'SHA256' 'ef3d913977c442c50230a7da755f5ea30cfb5fd6124b918b9555147972a5c9bb'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188401-188412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188401-188412.nc' 'SHA256' '69a609332673f290496a1769a6fecbf9c994d69a5079599f114d253a71158518'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188501-188512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188501-188512.nc' 'SHA256' 'f5ca9fe39cfc3803c6a38c0bb146f0948bf8e3deaf34bb895874a4b825f7705d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188601-188612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188601-188612.nc' 'SHA256' 'dba6c808e6713ea5c947770253466056fd47e60983329aaebc126b3d9c4e79fd'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188701-188712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188701-188712.nc' 'SHA256' '0ba948d9178324409ffd970355772931ae76ffdfa991d65fc6bbb2be7812a562'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188801-188812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188801-188812.nc' 'SHA256' '79968b0be148a3b6627c678011d5da451b165fc036196c1db8b20b88b1979629'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188901-188912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_188901-188912.nc' 'SHA256' '9275697e65e038f831ef2d2ea6b311b77516b0b10a7adc08a65b4f0776a68ecf'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189001-189012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189001-189012.nc' 'SHA256' '0822eabe5cf1f420aa9e4f01d3840b6a340b07bdb33f1401607a5eb4f458334c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189101-189112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189101-189112.nc' 'SHA256' '3536fb4ba67c6f601f5f0fc521a558e853fad8b87a022c7234bdf9ad0ac26563'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189201-189212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189201-189212.nc' 'SHA256' '8a6077e98c840758ec9bfa6e7af2b3633b44a091038f4a38e17e378f06e63691'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189301-189312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189301-189312.nc' 'SHA256' '86f5f731e4c0ec9e1edd048cc1fe1986511cec323bbaf0bd149ac2b5ec796ec1'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189401-189412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189401-189412.nc' 'SHA256' '9807305d3635ef12e2b8dcf63faf89aa7466edb1519b616b87cc2738c3700b7f'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189501-189512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189501-189512.nc' 'SHA256' '0c06015d8faf4c3e899d23d2a650f6fd3196f1d708f824fbdeb251e5841ce2c5'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189601-189612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189601-189612.nc' 'SHA256' '0ccf94fd744fed9edffb256bb6452696341c921b2bc54e61f56bb24e9ae296af'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189701-189712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189701-189712.nc' 'SHA256' '4bd496e5492da66636b7684cf07bcbb96463d0690afc9ed8d12b3db9a41b33d7'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189801-189812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189801-189812.nc' 'SHA256' '56fe3db9586fefef3496831bfcd0b91b51211c9b6f226eaf9b4d6812242e4c0c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189901-189912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_189901-189912.nc' 'SHA256' '7cb0904ec7ec37e3905cbf14ab8b51f36d0b34f1d8521ab638cd2cb162f43885'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190001-190012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190001-190012.nc' 'SHA256' 'cc73ec009ad0d618f0e63e4b30f0865facec7a7268458864015e3b73958438a9'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190101-190112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190101-190112.nc' 'SHA256' '31d77227ca4c791cf2f81198b3baf93807c33bb3e7e32324d174f65bf01f61ad'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190201-190212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190201-190212.nc' 'SHA256' 'a00b07ead3a9a283c0cfa40dd286b90c6614ab5fec8c7504ae12b38b39575666'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190301-190312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190301-190312.nc' 'SHA256' '9b41d64a57f4f99ead25e5cbd52dae964804ba507a1f2cb35d0ac61f95d950c8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190401-190412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190401-190412.nc' 'SHA256' '58c03d5f25121cf50611bbb7d83c1929b167e57d22fb31e14a49861daf164065'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190501-190512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190501-190512.nc' 'SHA256' '893093eaf6ea9138d7ea56fc0a52679da011a412bb34fd10b23990d727708ef8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190601-190612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190601-190612.nc' 'SHA256' 'd36864644ca0cb8dae7785751b2b1d019c73e964d320e99fe37f9a9cc1d7b194'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190701-190712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190701-190712.nc' 'SHA256' 'b820a5dab3aa82293f1891f7de144c0d56ee7df63c47d0b331e7f549f18486da'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190801-190812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190801-190812.nc' 'SHA256' '905d038b853c6fd864c1487b7cdddb8f5dfa666f87025cbdc3f7a25686332dbe'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190901-190912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_190901-190912.nc' 'SHA256' '4d71f9d96a92fbd3de2a5a8ae6b922ecc51a88bcee63af7bcec294c438f3dd0c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191001-191012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191001-191012.nc' 'SHA256' '4ea0c568242f18a9df87c00ac82e05df0f7d987b9d3778b44783e132f0c4982d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191101-191112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191101-191112.nc' 'SHA256' 'a1db01e4d4659cbcb238aee4b113bb35dd86e3214b9843601127fb94e957e766'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191201-191212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191201-191212.nc' 'SHA256' 'b9a773b80af6b44cab6c1f3338c8a7af48671f38f7ac01b7664f5a05dbaf84e3'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191301-191312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191301-191312.nc' 'SHA256' '1f62f61b71114bab60531ce8255aa4f12e5e34cb9674ddf2c2b15dfdb340dee3'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191401-191412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191401-191412.nc' 'SHA256' 'e9ddd9b69bff925287cf2a809f5a70ef130e04c7ee3520d37db2172fa02bd6d2'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191501-191512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191501-191512.nc' 'SHA256' 'de96eb2d657f44dcfbe7d40600471f90a2ad5c23b9155deae4fa9b4165def109'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191601-191612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191601-191612.nc' 'SHA256' '0ac1e1fee0794beecb0474603ed30a88c19a29952becc85308d9a9fc14e7ad0b'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191701-191712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191701-191712.nc' 'SHA256' '66a2a306ad45ff20a516f88eb1d7e8c02d61fd2b419a333d6fd5253d3f419884'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191801-191812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191801-191812.nc' 'SHA256' '247350cebd2f94f690916f2d67bfd59f61c5c209226e3fb7d2b960d6f2fc1d75'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191901-191912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_191901-191912.nc' 'SHA256' 'dc2939985f3bf7c48cbf514d3ac33f9f57513555e77f923e66288f4ecc0b27ff'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192001-192012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192001-192012.nc' 'SHA256' '249207bd1b6ec49595f7b3140a96079863789be730c259bbe720f6fa7f24996d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192101-192112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192101-192112.nc' 'SHA256' '4c5c59be15fd3559fc29ff9014ba0439fe299f146c70833e1928cc38d2c67114'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192201-192212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192201-192212.nc' 'SHA256' '7d09a78ff1215993d4785913bb3b39c7e0437be8241e4e0056dd5599ef73bcc9'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192301-192312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192301-192312.nc' 'SHA256' '23cad4d0ccd2c365477c95a2e4c1312799b92b5bc7dd85e79f391408a14349da'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192401-192412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192401-192412.nc' 'SHA256' 'fabdc92e308cd0d6fbc91e636037179f96ad91d8adadbcf59e90fc2a8558ad3b'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192501-192512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192501-192512.nc' 'SHA256' '845b6e87fb81716b481384e501d01417087476dcf8150914790c8b6824673eaf'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192601-192612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192601-192612.nc' 'SHA256' '056ee186ea571330a6e6c44c233a322b3a9ee7243773505705859fdc55671ccf'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192701-192712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192701-192712.nc' 'SHA256' '6735fe5931bbbad0f0a4fe870aee73dbc658cc15d67b57908cf757a1cdfcc92e'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192801-192812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192801-192812.nc' 'SHA256' 'e63a97a433d4a0c1749c0e7d2cd4a890a65e13459d8b94a6e024fbbbb0b65207'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192901-192912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_192901-192912.nc' 'SHA256' '43f796ab38d41d6c4bd783a33534cf6df489154e181d7af1971a2c1aa0d5ea37'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193001-193012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193001-193012.nc' 'SHA256' '7c6fe3609c2ea88453236bbbd2ffa540b231f5e3fc7f0083ea0cc07b0a4e7e7d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193101-193112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193101-193112.nc' 'SHA256' 'b22592e3fc24d91c4be4298ffe6162a11b8b7b243f4e083bfb54ed7bcf715a60'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193201-193212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193201-193212.nc' 'SHA256' 'cb364cecc56f140b1938838e096755355c5ed4f2f08cbd2f552854bd935cc395'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193301-193312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193301-193312.nc' 'SHA256' '98a390826b4496b567d258933d3f4bde722c5030a6048c2b37fbcc51ee0547df'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193401-193412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193401-193412.nc' 'SHA256' '4f779f68bbe2fc5470ad92baecd92ada11c602447feddabaf8d4252d3e4720d0'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193501-193512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193501-193512.nc' 'SHA256' '7ba4965dd6e53b11e17722e442a4eb65c8ac7326893dc189dfefb68bf0ad2b1f'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193601-193612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193601-193612.nc' 'SHA256' 'aee514ae376fde09c6d799e4c1644785d27a9f0a1cb02e1e53ab67006a3ce5ce'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193701-193712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193701-193712.nc' 'SHA256' '07416a8a90f436436c122297856213b3eb40d1af62f4f4d4e12d270323d7f21d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193801-193812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193801-193812.nc' 'SHA256' 'd67d390015bb7734cfa9f72524501be3cdda522492c5f80a14c07d11e7031015'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193901-193912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_193901-193912.nc' 'SHA256' 'e9cedf33daa4535bb7cea5bba8e6965cdb7ea193c13d4e0f236f44d77b5663e6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194001-194012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194001-194012.nc' 'SHA256' 'c2c9a81b3a4734124ee8cdef885f96d36d532750f7c257b240fcc19eac1033b6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194101-194112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194101-194112.nc' 'SHA256' 'a9fa6b93d4d633742c0af0dc9850ab3ef1d680faff0132d4df3a8928679bbf75'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194201-194212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194201-194212.nc' 'SHA256' 'efcc4a31ee3c3954fac068a4253a35ed5771add11eb53d1f3452663334c39806'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194301-194312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194301-194312.nc' 'SHA256' '9a1a56c3e8492b60286165126ffe0cefd1e7c04b0f258985e16b834c016d0549'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194401-194412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194401-194412.nc' 'SHA256' '60cd740f87a31916d6d60e14f06598ef4f5d15964e71847dc0df6e3ed620aefe'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194501-194512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194501-194512.nc' 'SHA256' '7ac88631bcc633a173cc8f9e8c79b42d9bc7995970de9d5e4b776ed0cef6d7dd'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194601-194612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194601-194612.nc' 'SHA256' 'bce8fc00ce74cf7779035cdc8e3dfa78ad8749c8539b55c1d5b13937afbfb60e'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194701-194712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194701-194712.nc' 'SHA256' '3c0fafb5bedaa5d07a7d37cae4fdb18322bf975faad7ce689de4c5574c8b1182'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194801-194812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194801-194812.nc' 'SHA256' '4aedbb7f4227d5daf1497df48ae6704eb1b1ded1d509f6d000b93b72790708d8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194901-194912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_194901-194912.nc' 'SHA256' '1c23247192ee3ec6728e81c0ae5563272a885b475772f492988bd942ea8254ba'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195001-195012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195001-195012.nc' 'SHA256' '17baaf59456dd57e9e51cd00f7929764e5c60b6feaaf3a7b210f581b50dc4fc1'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195101-195112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195101-195112.nc' 'SHA256' '30a0f3b2edf1362cca760f02af52e6ca682a39ca3f969a8d4d4c58a38660222b'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195201-195212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195201-195212.nc' 'SHA256' 'fbdd866da938488fd307c24d66686f667933b97af7301fe07d8d0e0b0dc74a1d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195301-195312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195301-195312.nc' 'SHA256' '0153028f98347622a1b5bfb8654152c6061d22ab8957a3a3d388f1a639126314'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195401-195412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195401-195412.nc' 'SHA256' 'ab9013c38cbf9a052768dfbb5ffdd0f94cad3f3e8fc10f8c6a8a07353be50eb5'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195501-195512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195501-195512.nc' 'SHA256' 'ad1ab9eded3e44bc6748b13860af02c6e19aa922b4bc0835a5cb0f6775a290cd'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195601-195612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195601-195612.nc' 'SHA256' '4a437d42262d84c1f7f74fb7691c33a5659c32d8e2d76115e4821ff62d2a3fea'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195701-195712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195701-195712.nc' 'SHA256' 'de6610d3f4e07d75b8306d7abe002dc1bbae3a596d3f559f69cb185feb9c026f'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195801-195812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195801-195812.nc' 'SHA256' 'bd95afcf650d5c15e32a12437c2ad88cc3d6d17c9c3414fc46c83f80c56f5104'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195901-195912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_195901-195912.nc' 'SHA256' '8cdaf223a588f08b128d0cf24fb5b07616e81ac8c851ca3f7cd140a651f828c7'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196001-196012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196001-196012.nc' 'SHA256' 'f3f744fbbf4d0862447c72dce0a3f1b2ae0fc0db0b5e9294db4cee88c46d2445'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196101-196112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196101-196112.nc' 'SHA256' 'f7a8b9a826e3a3f05b70e14f85fb98fbd47493c49c1a6c679c0204d8e9d8bd4b'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196201-196212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196201-196212.nc' 'SHA256' '216d7aa6f6a7fea5c61e2cec0e5d2f4f457ed2c9c666bcfd2e607336b9c82509'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196301-196312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196301-196312.nc' 'SHA256' '13e876ce31dbc9b1f7d03923c6a2e842403f6684986b84bdc232b59afbfeac42'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196401-196412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196401-196412.nc' 'SHA256' '93dedf5656506e7a1495339b634d4082d152d512ef0261edb8c259ec175e2f6c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196501-196512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196501-196512.nc' 'SHA256' '1f709c64deaab97a49960abf3e43a115373e98c93d5f0c2d95bd83a599e75c51'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196601-196612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196601-196612.nc' 'SHA256' '581aab0b3550f76ceb70d337142a6f84dae90ad486ecf885b0d0f56fd45791d4'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196701-196712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196701-196712.nc' 'SHA256' 'da493536c664cb8fa37b336155c5c211b5420a5fef77f287229a2a58283ddaa0'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196801-196812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196801-196812.nc' 'SHA256' '7b5209d6c072b077f65239e63f65bc510391d24e12235d3e95a7c14ce28555bc'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196901-196912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_196901-196912.nc' 'SHA256' 'e15a6c01c51157060b0940734de213ccfbaaa95b33bd5ed65bffce47ff315a06'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197001-197012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197001-197012.nc' 'SHA256' '6a8f501db6ef7238737c555383ff825be6dc822fc04b029640c8d436598c02d8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197101-197112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197101-197112.nc' 'SHA256' 'd4f1f7a24bd59e77f1ab2a48d38b8e58c79affa82161d9d4a0607c7a30f7d2a2'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197201-197212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197201-197212.nc' 'SHA256' 'a1c9907409916b29185e946872321a3e708d64a89e5199c2a0b13779033372e1'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197301-197312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197301-197312.nc' 'SHA256' 'af52f9d9315f4d7776496cbd4c395f17842634c5fcb2c46e4b9f2da706fa915d'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197401-197412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197401-197412.nc' 'SHA256' '5513ad9f11681786e5fb96b81e5c913c326498e869d4b5e8563db9bb6fdfa48c'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197501-197512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197501-197512.nc' 'SHA256' '74dfdcbfe6b525e193879597f5b9ebea99c6910edd7e865de402b303ce5d6884'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197601-197612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197601-197612.nc' 'SHA256' '5d9e84eb8c72741af27e41bb650d33b5c344f9599c43ad5c57c9853088995370'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197701-197712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197701-197712.nc' 'SHA256' 'ffd86afb114da1c253c17b53cd81caa41f774cb71a4d012c8c3cca8ded56da67'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197801-197812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197801-197812.nc' 'SHA256' 'fe76e2af202a5e5d941bd5dc498fc9eea8c78d98b8f0c3b830869be3b80114d6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197901-197912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_197901-197912.nc' 'SHA256' '5a5b300ecf5997d9baf0593e40fb378983f86bc5cb52ef0dc545a0e913b42ad8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198001-198012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198001-198012.nc' 'SHA256' 'cea56052a3a3bd5bd7c2842dc0e31bd3e860832de9c840e5edbca43addf2c9cb'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198101-198112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198101-198112.nc' 'SHA256' '8ab476a88c9d121dc27d91fd6c6d5f93219fc256f89d0bb31385f10cbef246d8'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198201-198212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198201-198212.nc' 'SHA256' '51c75db1e17f5a047dfe1c53a0b7190b2e66d81fe0a398ed40f1dce3d9895159'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198301-198312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198301-198312.nc' 'SHA256' '939a8e6273ffd2a542b9a941ede57e271ed66c56560d8d7a9162645b9a8e28c3'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198401-198412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198401-198412.nc' 'SHA256' '8de23b26607e7da53cb9764037eefadde8909604a8e1d9ad18af66e3cbcbd7c7'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198501-198512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198501-198512.nc' 'SHA256' '608079a3adc77c3c899e6fcedd034da7d1e3a2175eb9e433849d2737c763ca51'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198601-198612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198601-198612.nc' 'SHA256' 'aad1a295fe4ef2313e8a5169d245e7d9cbf04b5b145a60114d2bfc4775634b54'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198701-198712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198701-198712.nc' 'SHA256' 'a3241d41b7cd29cf268f346e45c1ef354453e945191ebd01fe31450e2f1e64fb'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198801-198812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198801-198812.nc' 'SHA256' 'd8e94c8ce80ae87e3484caf6ee72cf98c07a896d42817d395b1df045a29b6dc6'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198901-198912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_198901-198912.nc' 'SHA256' '25df1a42cc42d75d35d26d0a6a0eff564fc2d0cf780aba68e91ed02300d2df85'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199001-199012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199001-199012.nc' 'SHA256' 'bd7543eea56797e3421b97e2c3b575c45d84250c55fdad6b8450b06e9db9e924'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199101-199112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199101-199112.nc' 'SHA256' '287602fea992bb165a5eb3f3795ae4cffb042a9c405b8454152dba4806d64c79'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199201-199212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199201-199212.nc' 'SHA256' '469a52a15f4c7189130503d6bae0efb45257bf8304b0b5e9b8379d378e1813f1'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199301-199312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199301-199312.nc' 'SHA256' '8da4bb5d5b7de34b22f1f117f301cf96744e7953e03083b38797c62bc53c5494'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199401-199412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199401-199412.nc' 'SHA256' '26c58d1654aff954b87882aee42fe0f757836ac118dc4dc85ab5bbf0313bc8ff'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199501-199512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199501-199512.nc' 'SHA256' 'a1795ac1cb4397ec7880de9f474c69b3409737e5b0650c684a4544d7422216cb'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199601-199612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199601-199612.nc' 'SHA256' 'fea349d082053ecc26f6be833dff2e5d69c603371cf95cfa64d72e41adb4ecce'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199701-199712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199701-199712.nc' 'SHA256' '9b94f191eabf08febef41274fdc5e717d69c6255c060871d56fa283bd03748d3'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199801-199812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199801-199812.nc' 'SHA256' '9e13c6618761711c6583395d5ef71466d8ce82860820ca8bd41c524046d36990'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199901-199912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_199901-199912.nc' 'SHA256' 'e5c8306a014996c19f964167760f3ffa815c2169a4fd879a7c6af15c70634051'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200001-200012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200001-200012.nc' 'SHA256' 'c266e9720a43cc96e2502617ed41efc24b7d928ad3c1b5628834999a376f5861'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200101-200112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200101-200112.nc' 'SHA256' '80103d2fd705291a0649716769554f6f3c9b9af11bb44367cc660de591f2cefc'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200201-200212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200201-200212.nc' 'SHA256' 'f765765455d8e12a4cede7409770e1a5f884fac549894a0ad45c8e695038a80e'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200301-200312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200301-200312.nc' 'SHA256' 'c9f487bb5382db5ac0a18c492ffa262a4fe08428fe6cfbcc8e29c56df13ac036'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200401-200412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200401-200412.nc' 'SHA256' '9716967a9f81e27f2339710212f71fca5cc1e71a9f6f1bb72438d55180c74b67'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200501-200512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200501-200512.nc' 'SHA256' '04c95e44d59976cc0c689fc0750a8c98e6456e8814064c895828d59b36b4abfd'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200601-200612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200601-200612.nc' 'SHA256' '23f4f6bf9ca7891872ca313a47847a87bfa3a7ce5a91b1d642278176510eb80e'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200701-200712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200701-200712.nc' 'SHA256' '1a0c363b4bf047b10bdba1b9aaa66aad2756c71b976d0266cb341e87ef92df2b'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200801-200812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200801-200812.nc' 'SHA256' 'be66f0d7bb8b0465c350d21fbc977985b6dc74f9e0217fe81ca0a527eb9c45f2'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200901-200912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_200901-200912.nc' 'SHA256' '3d746cf474824f6700f6cb89b2dc45c3987dccae03819e327f88278c8ecadfd9'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201001-201012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201001-201012.nc' 'SHA256' '7b45366ce1468e26ca398d2ad2ff9b5ded35d01a3de61d2f1f867c6f0e12ca31'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201101-201112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201101-201112.nc' 'SHA256' '905a07f5b44ec20064568ad25030d4937b3e57c49c5a91bffcca269510a2d6b7'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201201-201212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201201-201212.nc' 'SHA256' '207ef6fb4053d5a3866612a8e0d7149d7829ad82534c2b87d1cdb0a19e18d775'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201301-201312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201301-201312.nc' 'SHA256' '74037dfcc73e2cf2c392e080a1a76fbdbb90eadad261b8f8fe8abdb8dc44bcbb'
'pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201401-201412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/CMIP/EC-Earth-Consortium/EC-Earth3/historical/r1i1p1f1/Amon/pr/gr/v20200310/pr_Amon_EC-Earth3_historical_r1i1p1f1_gr_201401-201412.nc' 'SHA256' '1df4967c0c1e2288961bf1c8a8188cfa5845e1dfdf8634f23a6fab5744c717d6'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 165 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
