#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esgf-node.ipsl.upmc.fr - 2025/06/23 12:35:49
# Search URL: https://esgf-node.ipsl.upmc.fr/esg-search/wget?distrib=true&latest=true&replica=true&realm=atmos&project=CMIP6&experiment_id=ssp585&frequency=mon&table_id=Amon&member_id=r1i1p1f1&variable=ua&source_id=EC-Earth3&limit=10000
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esgf-node.ipsl.upmc.fr/esg-search/wget?distrib=true&latest=true&replica=true&realm=atmos&project=CMIP6&experiment_id=ssp585&frequency=mon&table_id=Amon&member_id=r1i1p1f1&variable=ua&source_id=EC-Earth3&limit=10000'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201501-201512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201501-201512.nc' 'SHA256' '4a606ffb5f48f3ed5567785e6978788d800b7d6b59b2e101921bbe53b5f84d16'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201601-201612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201601-201612.nc' 'SHA256' 'e87012f48b50982fedf18c2a659208db19e683c873f66518018573b5b2da64eb'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201701-201712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201701-201712.nc' 'SHA256' 'd1d88ef5987c5cd15caf5eed5d1a0fc26acad5e7f74db1fe209b86131f93c1ec'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201801-201812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201801-201812.nc' 'SHA256' '7fbdc92d1b18e1201943684cadb32a6f6a0179f31659500371e80b6d0439726e'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201901-201912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_201901-201912.nc' 'SHA256' '91e7887394a305c298883e37e8b3b0cb20c124b00bfa19df9874e6ddad44871e'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202001-202012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202001-202012.nc' 'SHA256' '80f79b211a88dc48acc8e559b312be98107c3714fbc2ad5afea401f7cc27df63'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202101-202112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202101-202112.nc' 'SHA256' '0453db882f8eb24c6db91cfa064fd59009f684b28e606a0663cc9c8fb8a48f2b'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202201-202212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202201-202212.nc' 'SHA256' '87bd83320b7c20c66ce23f5e4d3f30f36a140f4799ae18cd7bff79adc3a35abc'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202301-202312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202301-202312.nc' 'SHA256' '882bc9422d653fcf58feb1fc0527cfe74fd9318b2cf9604da542922ad06fb31c'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202401-202412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202401-202412.nc' 'SHA256' 'd2760a5ba255425f2e0920dd239e5feb092b4db34f9f3166858b019ac1a4cd0a'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202501-202512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202501-202512.nc' 'SHA256' '870e78e4f3746ddd8a5b1c5a0dd3ba2e6e43d9105b60708bf7c8b6b51252e3c2'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202601-202612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202601-202612.nc' 'SHA256' 'b9f34a248b0f55e2b097103bea320bf471af10909d74ac6e053b8c9318b981da'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202701-202712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202701-202712.nc' 'SHA256' 'e76246501b9c27dd13ec88949a5bc658706ea16dd495a818044ab068f2029752'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202801-202812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202801-202812.nc' 'SHA256' '817284e48c8d9cff6fea56bc5f02b2e51eeae20cc75fb0e558a70295329a4a17'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202901-202912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_202901-202912.nc' 'SHA256' '2db124521ac6ee23580ed35aafed6a46ab1041fee3e06c926d1a48963def5e8d'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203001-203012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203001-203012.nc' 'SHA256' 'abe90f77fa344fc9bd5864ebb0eb7df4a7ea54cfb152d57c9e9bd5bfd7854b34'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203101-203112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203101-203112.nc' 'SHA256' '94424287ef57be90da250db3b729170fec487652e2d8920a5635bf82d85aa9f4'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203201-203212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203201-203212.nc' 'SHA256' '8f44a9865e9a869d5fe18998b0208f3b72e42e9efbebaba1cc7f5756cbac17c4'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203301-203312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203301-203312.nc' 'SHA256' '52d0e42c24df19304f78dac608ef2f2106d5694cd206e114d6f287fc16ff4876'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203401-203412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203401-203412.nc' 'SHA256' 'cb87f2f03771ff6f48902b0955b1b3675388926b007615c1a643e8d6d8d95296'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203501-203512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203501-203512.nc' 'SHA256' '6bdfc6c640909e92135bdcbbd77e0272a7e24ecac2835ba8c38f823bab595b9d'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203601-203612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203601-203612.nc' 'SHA256' 'c690b0e553c8d315d26eaea382315422bb5c5c90c5c873b42ccdbae8ca8b7012'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203701-203712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203701-203712.nc' 'SHA256' '7d3c9560e2b921ded853d014d8159a38bf548264028badab688e85f6bd96a579'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203801-203812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203801-203812.nc' 'SHA256' 'b8cff3396686511adbb5aaef4b8c7d309dd9ecc6374b95ce0e72994e0e0aedfb'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203901-203912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_203901-203912.nc' 'SHA256' 'cded385941139684401839485ca64afce87893e27bb12fe42523e99d001b3be1'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204001-204012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204001-204012.nc' 'SHA256' '1954ab004310061739e1266c11e8a9fc90f29b2565c44d366229be3206f485ac'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204101-204112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204101-204112.nc' 'SHA256' '277d8c7ed520219e6f5751e459c8361674dc7ec0eeba5c408dfa52d649742010'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204201-204212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204201-204212.nc' 'SHA256' 'e644e1303fc333f44ec6966e4f7d520800770a58d3fd25a4fbe77f3919d779da'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204301-204312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204301-204312.nc' 'SHA256' 'cace15139b07f3b465f6356c044e24ce90a6d63082685949d4931b477b848985'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204401-204412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204401-204412.nc' 'SHA256' '857265a0e85b9c3fc306a403cbda12c66324c264e5ba78f993c127046f618d8a'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204501-204512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204501-204512.nc' 'SHA256' 'fa3ee331ff1ede3fabf881696a4ae8f467a6a785f52c9c2205e758a7eb261f84'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204601-204612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204601-204612.nc' 'SHA256' '7e6c42a025a85a362083d5c5fe06e31278441d559a1a2ef1f38d52e891009914'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204701-204712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204701-204712.nc' 'SHA256' '10054feb45c2784a76b025a9014f8fdf7e4b619b6586e75e3a002589d61f71c3'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204801-204812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204801-204812.nc' 'SHA256' 'ef86be77a871d2969da5a649b90203232983a9c07c1c514e9b99adb924d59a2c'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204901-204912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_204901-204912.nc' 'SHA256' '97a604f2c8a7ba06635eb3ecd5332a458f306898093d84f3d333e53ab8728e11'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205001-205012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205001-205012.nc' 'SHA256' '367aa1d23bec14abeb8161b05e4ed363f449bfcdb9bd24b7bb272dc54378730c'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205101-205112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205101-205112.nc' 'SHA256' '4f66667e3967a638d1f73c238130370faf7710650963455a5d9d2eeebcbbd7df'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205201-205212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205201-205212.nc' 'SHA256' 'e2bc3a753eaa8b27ac31bd409ed24dad213a29143d405b9d5748436c562d99eb'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205301-205312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205301-205312.nc' 'SHA256' 'ae55f7e605adb7e609c35d239464f55f24f5d3312331b4662d970d05e58f9b07'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205401-205412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205401-205412.nc' 'SHA256' '542f2dea8cb3b369376f031ec4e15557e64bde96c8f3170e16fedda274ec2e3c'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205501-205512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205501-205512.nc' 'SHA256' 'e1872d6ba9eb1d1bd496d7ca3bed027b1b5c0bc50aec7fe8dc2574b0f0d8683d'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205601-205612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205601-205612.nc' 'SHA256' '7d9802761c0fd0524482b01009390686a432b374e16f48454d5daa41624ed363'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205701-205712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205701-205712.nc' 'SHA256' 'e57e1df8f3800681f69e65b4dfdd43cee751bccb840aae37b16e3b240e4a1d9e'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205801-205812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205801-205812.nc' 'SHA256' 'b06359e0a8c49dabc3111fb2b6dcfca261f8cf294ec5428b302ad99875416596'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205901-205912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_205901-205912.nc' 'SHA256' '84a9416e72afd064c0a925a9877ac6de33700a526675b582cee14da1e12081c1'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206001-206012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206001-206012.nc' 'SHA256' '234e0f8da1df6a625ba158759607088523fe047c73539cc5fa452d34559c8305'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206101-206112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206101-206112.nc' 'SHA256' 'f6bb2d1d51a607659f0274a41963c99db1193ef9d856dc97905ccf3b4f561586'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206201-206212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206201-206212.nc' 'SHA256' '68eaf8c68491271b8d5ce6aa093f1dc7869b4e76706febe92fb87478624ae867'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206301-206312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206301-206312.nc' 'SHA256' '50265dd0dff776f8a706c0b51b8ff6d75abb18ce254e46f0343e6a6c5075a538'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206401-206412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206401-206412.nc' 'SHA256' '983dab36dbc2a6df8fcc405cee5844397e8bbff60904639ace912e40eb1c9d32'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206501-206512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206501-206512.nc' 'SHA256' '70e2764b76e89d641e341c12a2e9d77549b60aabc7d94057d0f23bdd33771432'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206601-206612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206601-206612.nc' 'SHA256' 'cfb0c58c61d49dfbfbcb3b66004403b5a9feeff80c14c219dce2f8b28b4523a3'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206701-206712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206701-206712.nc' 'SHA256' 'eb56316be9f301cfffb9f1a56acf1b73cd29d38551b4573f584943677db4896e'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206801-206812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206801-206812.nc' 'SHA256' 'adcb314fdc201a0216b1796bfe665a53d9152764da2cc2b7154c55ca27e8aaea'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206901-206912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_206901-206912.nc' 'SHA256' 'e11b2e8503893c3dc50c3c90a75ac01ce6e4ba726f87a56c7bff2ec70ab0b77a'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207001-207012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207001-207012.nc' 'SHA256' 'a6537a118c704f504af4f01cb1b35d5f1186852f1b91896ec6a8bce8d7cf2070'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207101-207112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207101-207112.nc' 'SHA256' 'c3e38c3c13d00427d57fed9a456153ed22f08980c0d935c92cf080452495176d'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207201-207212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207201-207212.nc' 'SHA256' 'f89305e777e704f5f17a7f556c0aed205e0ef3407908db8cfe218054f93e7d41'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207301-207312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207301-207312.nc' 'SHA256' 'f32e7399e17d43b7520252e9ab58f7bc2ae743de6c247ba50e6beeaa717d394e'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207401-207412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207401-207412.nc' 'SHA256' '5e60723ccbfab78f0192b019dd3fbc855a740b53eaafbf4feb2fac6662e724e0'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207501-207512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207501-207512.nc' 'SHA256' 'a9d538f1faf323aacb69355e1d7d41532e712bf95cdd098c645acbc6820aba05'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207601-207612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207601-207612.nc' 'SHA256' '48c3338cf2f6c0e48064f281da33a971f0a6c307b2ef7ea0259c71e98a26b635'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207701-207712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207701-207712.nc' 'SHA256' '4e9bc13f2802a606f2028d98467b5a7f6fb851e91e6bce73b5bf16f8babe7a8a'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207801-207812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207801-207812.nc' 'SHA256' '88383a129566c568f7db0844ce8d0e2d619fcbd30f57907ce0e825c6dc78adde'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207901-207912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_207901-207912.nc' 'SHA256' 'b3777acf080a1790a1a4c1713b862e036af25cfe978c48608181b86aa27a2883'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208001-208012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208001-208012.nc' 'SHA256' '3d62a9c3d1f407f76cd4594230e57d88ad08f887a8dcaf75582ddf775e67529b'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208101-208112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208101-208112.nc' 'SHA256' '7846e91f58b18083640da5012c57862f19cc0e0472e96da50bff17352a161070'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208201-208212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208201-208212.nc' 'SHA256' 'f5a892ac58636a6e41dd5ed652059a984d12eb804abcbb70edca65825a430d62'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208301-208312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208301-208312.nc' 'SHA256' 'd6d407030793e6cdc70e5759511bd455007ca0d22d311bbf70a9ed9a93f3223c'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208401-208412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208401-208412.nc' 'SHA256' 'e6f733d33b02476759bc5c095348d8b508b783efece0e0908d795b0ecd58df1b'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208501-208512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208501-208512.nc' 'SHA256' 'ae99510fb8158dfec8b7b5248082b0e2c3a3b8f74bd279972d72bf15e355a899'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208601-208612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208601-208612.nc' 'SHA256' '410e88b57c8e3ff031913bb45eae3ab3689ae9125c822acacf7664b38fdf7cb8'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208701-208712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208701-208712.nc' 'SHA256' 'de55f4476801e763662729a6501d87694cc33bcf20d1c0cff16e7be6465ae589'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208801-208812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208801-208812.nc' 'SHA256' 'a87fbc98ffa8b136d732fe7201b4a43db60e75be8f6ad755ac54612633682481'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208901-208912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_208901-208912.nc' 'SHA256' 'b38a1b1fce9970b1e74c9ae99ca6b93e8797a369682cadf4b4b11091adeca1d2'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209001-209012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209001-209012.nc' 'SHA256' '184e846713c0441864365e04a86aad9db6fe15a3955610d6aa9673054412f6cf'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209101-209112.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209101-209112.nc' 'SHA256' 'f94e554afec9c43fdf55d45681973e85cc70cae76d9d0db2bdedc6cd04c8668f'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209201-209212.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209201-209212.nc' 'SHA256' '3913771a4155fdceb6361dd0274dd6f758bc6d3e7a0c48da9e0141621fdf45d4'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209301-209312.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209301-209312.nc' 'SHA256' '88a1bdca32513536951f09b6f59b4a9887f327b7fb96e2272e32e50d7553a00c'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209401-209412.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209401-209412.nc' 'SHA256' 'f14636dc9313c6c6d8f5ba49b3b6dcfb3bc1e5771507ad14f633350150761465'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209501-209512.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209501-209512.nc' 'SHA256' '0624350fd75b5e750924767193b767f5c5616da53af090519de5593399536871'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209601-209612.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209601-209612.nc' 'SHA256' 'd945cda2f4952d39b1c61c686dae9d6fb1bbe81ef6c6ad503835411dc0a09c90'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209701-209712.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209701-209712.nc' 'SHA256' '67a49b29644dadc6757ac09292ba20cae67c25335e3833f32a4616cdfd1fb258'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209801-209812.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209801-209812.nc' 'SHA256' '90e304c3c9ca47355c54cdc5c0c6d9bcf6971ec49dbc69d096f51dc038131275'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209901-209912.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_209901-209912.nc' 'SHA256' '67d90392edb286874c6f02dabcf2460a6be2b1294613733a5996c651ba177efb'
'ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_210001-210012.nc' 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/ScenarioMIP/EC-Earth-Consortium/EC-Earth3/ssp585/r1i1p1f1/Amon/ua/gr/v20200310/ua_Amon_EC-Earth3_ssp585_r1i1p1f1_gr_210001-210012.nc' 'SHA256' '57ea49cf628f700ae147b155f3d1be04815b40ce2add7b5cad22d261d11e39c3'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 86 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
